### PR TITLE
Adds + applies black formatter pre-commit hook.

### PR DESCRIPTION
**Pull request by djsaunde**

### CODE REVIEW

**Comment by velocirabbit** [comment]
This formatter puts closing parenthesis on a new line, rather than at the end of the last line in the parenthesized block of code. Could we change that to follow Google's style guide, or are we moving away from that with this? I'm personally open to either.

**Comment by djsaunde** [comment]
@velocirabbit black is an opinionated formatter, which means it doesn't really allow changes (https://black.readthedocs.io/en/stable/the_black_code_style.html). I'm personally against Google's style guide because (1) it doesn't always follow PEP8, and (2) PEP8 is usually supported (violations are flagged / fixed) by IDEs + formatting software (like black). Code style gets taken care of automatically so we don't have to spend code review time on it.

**Comment by jimfleming** [comment]
I agree. I don't care what the styles are as long as its consistent.

**Comment by velocirabbit** [comment]
@djsaunde That makes sense. It just isn't consistent with how we've formatted the closing parenthesis in the past, but having a formatter makes things more convenient.

**Pull request merged**
